version: '3'

services:
  nginx:
    build:
      context: ./nginx
    image: hrodrigues/nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    build:
      context: ./node
    container_name: app
    networks:
      - node-network
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - dados

  dados:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: dados
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network


networks:
  node-network:
    driver: bridge